version: '2.4'
services:
  nginx:
    container_name: my_lemp-nginx #название контейнера
    hostname: my_lemp-nginx #название хоста 
    build: ./build/nginx #тут лежит докерфайл
    volumes:
      - ./log/nginx:/var/log/nginx:z #log файлы nginx.
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:z #Конфигурация nginx.
      - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled:z #Конфигурация моего веб сервера.
      - ./var/www:/var/www/my_lemp:z 
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
    restart:
      always
    networks:
      default:
        ipv4_address: 172.16.1.4
  php-fpm:
    container_name: my_lemp-php-fpm
    hostname: my_lemp-php-fpm
    build: ./build/php #тут лежит докерфайл
    ports:
      - "9000:9010"
    volumes:
      - ./log/php:/var/log/php:z #log файлы php.
      - ./etc/php/fpm.pool.d/domain.conf:/usr/local/etc/php-fpm.d/domain.conf:z #Конфигурация для моего веб-сервера
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:z #Конфигурация php для php-fpm
      - ./var/www:/var/www/my_lemp:z
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    restart:
      always
    networks:
      default:
        ipv4_address: 172.16.1.5
  mysql:
    container_name: my_lemp-mysql
    hostname: my_lemp-mysql
    build: ./build/mysql #тут лежит докерфайл
    ports:
      - "3310:3310"
    environment:
      MYSQL_ROOT_PASSWORD: tartar2002
      MYSQL_DATABASE: lemp_db
    command: --init-file /data/application/init.sql #дамп бд
    volumes:
      - ./init.sql:/data/application/init.sql:z #файл дампа базы данных
      - ./db:/var/lib/mysql:z
      - ./log/mysql:/var/log/mysql:z #log файлы mysql.
      - ./etc/mysql/conf.d:/etc/mysql/conf.d:z #Конфигурация mysql.
    networks:
      default:
        ipv4_address: 172.16.1.6
    restart:
      always

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.1.0/24
